name: $(version)

variables:
  version.major: 21
  version.minor: 0
  version.update: 0
  version.phase: d
  #version.name: ${{ format('{0}.{1}.{2}{3}', variables['version.major'], variables['version.minor'], variables['version.update'], variables['version.phase']) }}
  version.name: 21.0.0d
  ${{ if eq(variables['version.name'], '') }}:
    version.revision: $[ counter(variables['version.name'], 53) ]
  ${{ if ne(variables['version.name'], '') }}:
    version.revision: $[ counter(variables['version.name'], 40) ]
  version: $[format('{0}{1}', variables['version.name'], variables['version.revision'])]
  buildsdk: ${{parameters.buildsdk}}
  buildfeed: ${{parameters.buildfeed}}

parameters:
  - name: buildsdk
    displayName: Build SDK?
    type: boolean
    default: false
  - name: buildfeed
    displayName: Build package feed?
    type: boolean
    default: false

trigger:
- main

pool:
  name: agates-test

steps:
- script: echo $(isName)